version: '{build}'

shallow_clone: true

os:
  - Windows Server 2012

platform:
  - x64

environment:
  global:
    MB_SLOW_TEST_TIMEOUT: 120000

  matrix:
    - MB_APPVEYOR_CONFIG: "NODE_VERSION=10|MB_GRUNT_TASK=outOfProcessImposters default|MB_PORT=3535"
    - MB_APPVEYOR_CONFIG: "NODE_VERSION=6|MB_GRUNT_TASK=test:zip|MB__PORT=3535"

cache:
  - node_modules -> package.json

init:
  - git config --global core.autocrlf true

install:
  - ps: |
          $version = Get-ChildItem env:MB_VERSION
          ForEach ($var in (Get-ChildItem env:MB_APPVEYOR_CONFIG).Value.Split("|")) {
              $key = $var.Split("=")[0]
              $value = $var.Split("=")[1].Replace("MB_VERSION", $version.Value);
              Set-Item env:$key $value
          }
  - ps: Install-Product node $env:NODE_VERSION

build_script:
  - node --version && npm --version
  - build.bat %MB_GRUNT_TASK%

test: off
